require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe OrdersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Order. As you add validations to Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    "5 VS5\r\n14 MB11\r\n11 CF"
   }

  let(:invalid_attributes) {
   "5 VS5\r\n14 MB11\r\n11 CF"
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Order" do
        expect { post :create, params: {products: valid_attributes}, session: valid_session}.to change(Order, :count).by(1)
      end
      # it "redirects to the created order" do
      #   post :create, params: {order: valid_attributes}, session: valid_session
      #   expect(response).to redirect_to(Order.last)
      # end
    end

    context "with invalid params" do
      it "returns back to products page" do
        post :create, params: {products: invalid_attributes}, session: valid_session
        expect(response).to redirect_to(order_path(Order.last))
      end
    end
  end

end
